In [1]:
import torch
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
words = open("names.txt", "r").read().splitlines()

In [3]:
len(words)

32033

In [4]:
words[:5]

['emma', 'olivia', 'ava', 'isabella', 'sophia']

In [5]:
chars = sorted(list(set(''.join(words)))) 
chars

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [6]:
# Build the mappings
stoi = {ch: i+1 for i, ch in enumerate(chars)}
stoi['.'] = 0
itos = {ch: i for i, ch in stoi.items()}

itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [13]:
# Build the dataset
block_size = 3
X, Y = [], []

for w in words[:5]:
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        context = context[1:] + [ix]


In [14]:
X = torch.tensor(X)
Y = torch.tensor(Y)

In [16]:
X.shape, Y.shape, X.dtype, Y.dtype

(torch.Size([32, 3]), torch.Size([32]), torch.int64, torch.int64)

In [18]:
C = torch.randn((27, 2))

In [20]:
C[5]

tensor([-0.4974, -2.8727])

In [22]:
C[X].shape

torch.Size([32, 3, 2])

In [25]:
X[1]

tensor([0, 0, 5])

In [27]:
C[X[1]]

tensor([[ 0.8008,  1.2754],
        [ 0.8008,  1.2754],
        [-0.4974, -2.8727]])

In [28]:
emb = C[X]
emb.shape

torch.Size([32, 3, 2])